name = "medium-backend"
main = "src/index.ts"
compatibility_date = "2025-02-06"

[vars]
JWT_SECRET="pm1234"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTFhYzI0YTAtZjBhYS00ZTA2LWEzOTEtMTEzMTY1ZWMzOTdkIiwidGVuYW50X2lkIjoiZjFjYmViOWMyNDJhOGE1ODI1NGFlZTkyMGQyY2NhNWQ1MTZmNjA0YjQ3ZmM2ZDZlMGY1NDkxZDA2MzkxOWEwMiIsImludGVybmFsX3NlY3JldCI6ImNiOWE2ZmJlLTg3NzMtNDhiOS04YmQ2LTg3NjBjOTdlY2E2MCJ9.OizUZAa9vlqOb9MviDNdyOpU8XyKLOqsZH3CJ2Pnk-4"


# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1